version: 1
name: Java with Gradle without clone node
stages:
  - name: Build and test Java app
    type: ci
    spec:
      steps:
        - name: Build
          type: script
          spec:
            run: |-
              echo "Hello world"