version: 1
name: Java with Gradle clone disabled
stages:
  - name: Build and test Java app
    type: ci
    spec:
      clone:
        disabled: true
      steps:
        - name: Build
          type: script
          spec:
            run: |-
              echo "Hello world"