version: 1
name: Java with Gradle Remote Clone
stages:
  - name: Build and test Java app
    type: ci
    spec:
      clone:
        disabled: false
        repository:
           connector: GitHubAccount
           name: harness-core
           branch: develop
      steps:
        - name: Build
          type: script
          spec:
            run: |-
              echo "Hello world"