version: 1
name: Java with Gradle 4
stages:
  - name: Build and test Java app
    type: CI
    spec:
      strategy:
        parallelism: 3
      clone:
        disabled: false
      steps:
        - name: Build
          type: script
          spec:
            run: |-
              echo "Hello world"
        - name: Run Tests
          type: run_tests
          spec:
            language: Java
            build_tool: Gradle
            build_args: test
            test_reports:
              type: JUnit
              paths:
                - "**/*.xml"