version: 1
name: Java with Gradle Remote Clone
stages:
  - name: Build and test Java app
    type: ci
    spec:
      clone:
        disabled: false
        repository:
           connector: RaghavGitConnector
           name: test-repo
           branch: main
      steps:
        - name: Build
          type: script
          spec:
            run: |-
              echo "Hello world"