version: 1
name: Java with Gradle steps parallel
stages:
  - name: Build and test Java app
    type: ci
    spec:
      clone:
        disabled: false
      steps:
        - name: Build
          type: script
          spec:
            strategy:
              parallelism: 3
            run: |-
              echo "Hello world"