pipeline:
  name: Rm2
  identifier: Rm2
  projectIdentifier: testapp
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: Build
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: account.CItestK8sConnector0H3jpA92Aq
              namespace: harness-qa-delegate
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  type: Run
                  name: "Echo "
                  identifier: Echo
                  spec:
                    connectorRef: docker2
                    image: alpine
                    shell: Sh
                    command: echo "hello"
                    envVariables:
                      aaa: <+pipeline.variables.ACCOUNT>
  properties:
    ci:
      codebase:
        connectorRef: RaghavPrivateGithub
        build: <+input>
  variables:
    - name: ACCOUNT
      type: String
      default: "682624005382"
      description: ""
      value: <+input>.allowedValues(635780325939,682624005382)
