pipeline:
  name: RmQA
  identifier: RmQA
  projectIdentifier: RaghavTest
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: Stage
        identifier: Stage
        description: ""
        type: CI
        spec:
          cloneCodebase: false
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: account.CItestK8sConnectorxwX9uT85io
              namespace: assa
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  type: Run
                  name: "Echo "
                  identifier: Echo
                  spec:
                    connectorRef: docker
                    image: alpine
                    shell: Sh
                    command: echo "hello"
  variables:
    - name: ACCOUNT
      type: String
      default: "608178844183"
      description: ""
      value: <+input>.allowedValues(635780325939,682624005382,355166347423,822078214230,608178844183)
