pipeline:
  name: RPtest
  identifier: RPtest
  projectIdentifier: RaghavTest
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: stage1
        identifier: stage1
        description: ""
        type: CI
        spec:
          cloneCodebase: false
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Sh
                    command: echo <+secrets.getValue("account.harnessoauthaccesstoken_gitlab_1691405278727")> | base64 --decode
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
