pipeline:
  name: RPtest
  identifier: RPtest
  projectIdentifier: RaghavTest
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: stage1
        identifier: stage1
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Sh
                    command: "echo <+secrets.getValue(\"account.harnessoauthsecrettoken_gitlab_1691410119545\")> | base64 "
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          caching:
            enabled: false
  properties:
    ci:
      codebase:
        connectorRef: RaghavTest
        build: <+input>
