version: 1
name: Yaml Remote_1671525577029
inputs:
  foo:
    type: string
    desc: image name
    default: golang
  repo:
    type: string
    desc: repository name
    required: true
    prompt: true
stages:
  - type: parallel
    spec:
      stages:
        - name: output variable
          type: ci
          spec:
            steps:
              - name: one test
                type: script
                spec:
                  image: alpine
                  run: |-
                    echo <+inputs.foo>
                    export foo=bar
                  shell: sh
                  outputs:
                    - foo
              - name: two
                type: script
                spec:
                  image: alpine
                  run: echo <+steps.one_test.output.outputVariables.foo>
                  pull: always
