---
version: 1
inputs:
  image:
    type: "string"
    desc: "image name"
    default: "golang"
stages:
- name: "output variable"
  type: "ci"
  spec:
    steps:
    - name: "one test"
      type: "script"
      spec:
        image: "<+inputs.image>"
        run: "export foo=bar"
        shell: "sh"
        outputs:
        - "foo"
    - name: "two"
      type: "script"
      spec:
        image: "alpine"
        run: "echo <+steps.one_test.output.outputVariables.foo>"
        pull: "always"
name: "Yaml Simp Remote - Clone"
